ncap2 -h -s 'defdim("nz_pm2p5_fraction_of_aitken_mode",70)' aero_gauss_state_F12.nc
ncap2 -h -s "pm2p5_fraction_of_aitken_mode[nz_pm2p5_fraction_of_aitken_mode,ny,nx]=1.0" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_pm2p5_fraction_of_accumulation_mode",70)' aero_gauss_state_F12.nc
ncap2 -h -s "pm2p5_fraction_of_accumulation_mode[nz_pm2p5_fraction_of_accumulation_mode,ny,nx]=1.0" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_pm2p5_fraction_of_coarse_mode",70)' aero_gauss_state_F12.nc
ncap2 -h -s "pm2p5_fraction_of_coarse_mode[nz_pm2p5_fraction_of_coarse_mode,ny,nx]=0.05" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aso4i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aso4i_wrt_dry_air[nz_mixing_ratio_of_aso4i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_ano3i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_ano3i_wrt_dry_air[nz_mixing_ratio_of_ano3i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_anh4i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_anh4i_wrt_dry_air[nz_mixing_ratio_of_anh4i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_anai_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_anai_wrt_dry_air[nz_mixing_ratio_of_anai_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_acli_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_acli_wrt_dry_air[nz_mixing_ratio_of_acli_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aeci_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aeci_wrt_dry_air[nz_mixing_ratio_of_aeci_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aothri_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aothri_wrt_dry_air[nz_mixing_ratio_of_aothri_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_alvpo1i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_alvpo1i_wrt_dry_air[nz_mixing_ratio_of_alvpo1i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvpo1i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvpo1i_wrt_dry_air[nz_mixing_ratio_of_asvpo1i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvpo2i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvpo2i_wrt_dry_air[nz_mixing_ratio_of_asvpo2i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_alvoo1i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_alvoo1i_wrt_dry_air[nz_mixing_ratio_of_alvoo1i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_alvoo2i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_alvoo2i_wrt_dry_air[nz_mixing_ratio_of_alvoo2i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvoo1i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvoo1i_wrt_dry_air[nz_mixing_ratio_of_asvoo1i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvoo2i_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvoo2i_wrt_dry_air[nz_mixing_ratio_of_asvoo2i_wrt_dry_air,ny,nx]=0.1" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aso4j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aso4j_wrt_dry_air[nz_mixing_ratio_of_aso4j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_ano3j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_ano3j_wrt_dry_air[nz_mixing_ratio_of_ano3j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_anh4j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_anh4j_wrt_dry_air[nz_mixing_ratio_of_anh4j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_anaj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_anaj_wrt_dry_air[nz_mixing_ratio_of_anaj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aclj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aclj_wrt_dry_air[nz_mixing_ratio_of_aclj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aecj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aecj_wrt_dry_air[nz_mixing_ratio_of_aecj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aothrj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aothrj_wrt_dry_air[nz_mixing_ratio_of_aothrj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_afej_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_afej_wrt_dry_air[nz_mixing_ratio_of_afej_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asij_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asij_wrt_dry_air[nz_mixing_ratio_of_asij_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_atij_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_atij_wrt_dry_air[nz_mixing_ratio_of_atij_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_acaj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_acaj_wrt_dry_air[nz_mixing_ratio_of_acaj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_amgj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_amgj_wrt_dry_air[nz_mixing_ratio_of_amgj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_amnj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_amnj_wrt_dry_air[nz_mixing_ratio_of_amnj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aalj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aalj_wrt_dry_air[nz_mixing_ratio_of_aalj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_akj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_akj_wrt_dry_air[nz_mixing_ratio_of_akj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_alvpo1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_alvpo1j_wrt_dry_air[nz_mixing_ratio_of_alvpo1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvpo1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvpo1j_wrt_dry_air[nz_mixing_ratio_of_asvpo1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvpo2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvpo2j_wrt_dry_air[nz_mixing_ratio_of_asvpo2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvpo3j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvpo3j_wrt_dry_air[nz_mixing_ratio_of_asvpo3j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aivpo1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aivpo1j_wrt_dry_air[nz_mixing_ratio_of_aivpo1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_axyl1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_axyl1j_wrt_dry_air[nz_mixing_ratio_of_axyl1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_axyl2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_axyl2j_wrt_dry_air[nz_mixing_ratio_of_axyl2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_axyl3j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_axyl3j_wrt_dry_air[nz_mixing_ratio_of_axyl3j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_atol1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_atol1j_wrt_dry_air[nz_mixing_ratio_of_atol1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_atol2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_atol2j_wrt_dry_air[nz_mixing_ratio_of_atol2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_atol3j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_atol3j_wrt_dry_air[nz_mixing_ratio_of_atol3j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_abnz1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_abnz1j_wrt_dry_air[nz_mixing_ratio_of_abnz1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_abnz2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_abnz2j_wrt_dry_air[nz_mixing_ratio_of_abnz2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_abnz3j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_abnz3j_wrt_dry_air[nz_mixing_ratio_of_abnz3j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aiso1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aiso1j_wrt_dry_air[nz_mixing_ratio_of_aiso1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aiso2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aiso2j_wrt_dry_air[nz_mixing_ratio_of_aiso2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aiso3j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aiso3j_wrt_dry_air[nz_mixing_ratio_of_aiso3j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_atrp1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_atrp1j_wrt_dry_air[nz_mixing_ratio_of_atrp1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_atrp2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_atrp2j_wrt_dry_air[nz_mixing_ratio_of_atrp2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asqtj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asqtj_wrt_dry_air[nz_mixing_ratio_of_asqtj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aalk1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aalk1j_wrt_dry_air[nz_mixing_ratio_of_aalk1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aalk2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aalk2j_wrt_dry_air[nz_mixing_ratio_of_aalk2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_apah1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_apah1j_wrt_dry_air[nz_mixing_ratio_of_apah1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_apah2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_apah2j_wrt_dry_air[nz_mixing_ratio_of_apah2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_apah3j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_apah3j_wrt_dry_air[nz_mixing_ratio_of_apah3j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aorgcj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aorgcj_wrt_dry_air[nz_mixing_ratio_of_aorgcj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aolgbj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aolgbj_wrt_dry_air[nz_mixing_ratio_of_aolgbj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aolgaj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aolgaj_wrt_dry_air[nz_mixing_ratio_of_aolgaj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_alvoo1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_alvoo1j_wrt_dry_air[nz_mixing_ratio_of_alvoo1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_alvoo2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_alvoo2j_wrt_dry_air[nz_mixing_ratio_of_alvoo2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvoo1j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvoo1j_wrt_dry_air[nz_mixing_ratio_of_asvoo1j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvoo2j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvoo2j_wrt_dry_air[nz_mixing_ratio_of_asvoo2j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asvoo3j_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asvoo3j_wrt_dry_air[nz_mixing_ratio_of_asvoo3j_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_apcsoj_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_apcsoj_wrt_dry_air[nz_mixing_ratio_of_apcsoj_wrt_dry_air,ny,nx]=0.2" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aso4k_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aso4k_wrt_dry_air[nz_mixing_ratio_of_aso4k_wrt_dry_air,ny,nx]=0.5" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_asoil_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_asoil_wrt_dry_air[nz_mixing_ratio_of_asoil_wrt_dry_air,ny,nx]=0.5" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_acors_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_acors_wrt_dry_air[nz_mixing_ratio_of_acors_wrt_dry_air,ny,nx]=0.5" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aseacat_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aseacat_wrt_dry_air[nz_mixing_ratio_of_aseacat_wrt_dry_air,ny,nx]=0.5" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_aclk_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_aclk_wrt_dry_air[nz_mixing_ratio_of_aclk_wrt_dry_air,ny,nx]=0.5" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_ano3k_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_ano3k_wrt_dry_air[nz_mixing_ratio_of_ano3k_wrt_dry_air,ny,nx]=0.5" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mixing_ratio_of_anh4k_wrt_dry_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mixing_ratio_of_anh4k_wrt_dry_air[nz_mixing_ratio_of_anh4k_wrt_dry_air,ny,nx]=0.5" aero_gauss_state_F12.nc
ncrename -h -v dry_air_density_levels_minus_one,ori_dry_air_density_levels_minus_one aero_gauss_state_F12.nc
ncap2 -h -s "dry_air_density_levels_minus_one[nz_dry_air_density_levels_minus_one,ny,nx]=1.0" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_dry_air_density",70)' aero_gauss_state_F12.nc
ncap2 -h -s "dry_air_density[nz_dry_air_density,ny,nx]=1.0" aero_gauss_state_F12.nc
ncap2 -h -s 'defdim("nz_mass_density_of_particulate_matter_2p5_in_air",70)' aero_gauss_state_F12.nc
ncap2 -h -s "mass_density_of_particulate_matter_2p5_in_air[nz_mass_density_of_particulate_matter_2p5_in_air,ny,nx]=11.375" aero_gauss_state_F12.nc
